### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kashif-ghafoor** [0x80/isolate-package#118]
I am trying to deploy a package to google cloud function. And getting following error when I run `npx isolate` in target packages' root directory.

Error: `RangeError: Maximum call stack size exceeded`

**debug output**:
```
info Using isolate-package version 1.20.0
debug Found tsconfig at: ./tsconfig.json
debug Workspace root resolved to /Users/kashif/development/dsrc
debug Isolate target package (root)/functions/detect-unterminated-feeds
debug Isolate output directory (root)/functions/detect-unterminated-feeds/isolate
debug Cleaned the existing isolate output directory
debug No packageManager field found in root manifest
debug Detected package manager pnpm 9.15.1
debug Use PNPM pack instead of NPM pack
debug Override workspace packages via config: node/*
debug Registering package node/feeds
warning Ignoring directory node/deployment because it does not contain a package.json file
debug Registering package node/db
debug Registering package node/da
debug Registering package node/codegen
warning Ignoring directory node/@da because it does not contain a package.json file
warning Ignoring directory node/@codegen because it does not contain a package.json file
warning Ignoring directory node/@browser-websocket because it does not contain a package.json file
RangeError: Maximum call stack size exceeded
    at file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:33:9
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:29:59)
    at file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:31:7
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:29:59)
    at file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:31:7
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:29:59)
    at file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:31:7
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:29:59)
    at file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:31:7
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:29:59)
    at file:///Users/kashif/development/dsrc/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/src/lib/registry/list-internal-packages.ts:31:7

```
    

isolate.config.json
```
{
  "logLevel": "debug",
  "workspacePackages": ["node/**"]
}
```

package.json
```
{
  "name": "package-name",
  "version": "1.0.0",
  "type": "module",
  "engines": {
    "node": "20"
  },
  "main": "dist/index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.4.2",
    "db": "workspace:*",
    "firebase-functions": "^6.2.0",
    "isolate-package": "^1.19.0"
  },
  "devDependencies": {
    "@types/node": "20.14.1",
    "typescript": "5.6.3"
  },
  "private": true,
  "files": [
    "dist",
    ".env"
  ]
}

```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "rootDir": "src",
    "moduleResolution": "NodeNext",
    "outDir": "dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "paths": {
      "db": ["../../node/db"]
    }
  },
  "compileOnSave": true,
  "include": ["src"],
  "exclude": ["node_modules"],
  "references": [
    {
      "path": "../../node/db"
    }
  ]
}
```

Node version: `v22.12.0`
OS: Macos

**Comment by kashif-ghafoor** [comment]
nvm 
db package that I am referencing in target package had a circular self-reference 
```
{
  "name": "db",
  "type": "module",
  "version": "0.0.1",
  "exports": "./dist/src/index.js",
  "private": true,
  "dependencies": {
    "db": "link:",
  },

}
``` 
which caused this issue.

**Comment by kashif-ghafoor** [comment]
removing circular self-reference resolved the issue
