### ISSUE TITLE
Failed to generate lockfile: value.startsWith is not a function

### ISSUE THREAD

**Issue by anasmohammed361** [0x80/isolate-package#119]
TypeError: value.startsWith is not a function
    at file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/isolate-package@1.21.0-1/node_modules/isolate-package/src/lib/lockfile/helpers/pnpm-map-importer.ts:48:16
    at o (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/remeda@2.19.0/node_modules/remeda/dist/chunk-S23N53O3.js:1:137)
    at u (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/remeda@2.19.0/node_modules/remeda/dist/chunk-RAAYCPUM.js:1:99)
    at i (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/remeda@2.19.0/node_modules/remeda/dist/chunk-S23N53O3.js:1:65)
    at pnpmMapDependenciesLinks (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/isolate-package@1.21.0-1/node_modules/isolate-package/src/lib/lockfile/helpers/pnpm-map-importer.ts:47:10)
    at pnpmMapImporter (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/isolate-package@1.21.0-1/node_modules/isolate-package/src/lib/lockfile/helpers/pnpm-map-importer.ts:24:9)
    at file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/isolate-package@1.21.0-1/node_modules/isolate-package/src/lib/lockfile/helpers/generate-pnpm-lockfile.ts:121:13
    at Array.map (<anonymous>)
    at generatePnpmLockfile (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/isolate-package@1.21.0-1/node_modules/isolate-package/src/lib/lockfile/helpers/generate-pnpm-lockfile.ts:111:9)
    at processLockfile (file:///home/anasmohammed361/vs/webzenith/hobbyfi/hobbyfi-web/node_modules/.pnpm/isolate-package@1.21.0-1/node_modules/isolate-package/src/lib/lockfile/process-lockfile.ts:83:7)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by anasmohammed361** [comment]
I currently use pnpm version - 9 and my lock file version is also 9
